default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['PASSWORD'] %>
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: shiori_development
  
test:
  <<: *default
  database: shiori_test

production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://railsguides.jp/configuring.html#データベース接続をプールする
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: shiori_app_production
  username: shiori_app
  password: <%= ENV['SHIORI_APP_DATABASE_PASSWORD'] %>